### ISSUE TITLE
does MTA-SMS validator present cached results

### ISSUE THREAD

**Issue by thomas-maeder** [aykevl/mta-sts#11]
Hi

MTA-SMS validator is a great service.

I have just implementated an improvement in the configuration of a server, but MTA-SMS validator still suggests the same improvement.

The reason may be that MTA-SMS validator still presents the result from before I made the improvement. That would be perfectly ok if
* the test result gave an indication on when it was established
* the test result gave an indication on how to get an updated result (e.g. wait for an hour or a day, or hit this and that button)

**Comment by aykevl** [comment]
The MTA-STS validator itself does not cache any results. However, DNS servers may cache lookups, so that is why you may be seeing stale results.

I hope that answers your question, if not please reply and I'll reopen.
