### ISSUE TITLE
Wildcard TLS certificates not recognized.

### ISSUE THREAD

**Issue by koehn** [aykevl/mta-sts#4]
My mail server (`mail.koehn.com`, used by domain koe.hn) uses a wildcard TLS certificate (`*.koehn.com`). Your otherwise fantastic tool doesn't recognize that this certificate is valid for this server. 

Thanks for the handy tool!

**Comment by aykevl** [comment]
Thank you for the report! You are correct, I made two mistakes with the translation of the wildcard matching algorithm from the spec. They are now fixed.

**Comment by koehn** [comment]
Thanks!
